# Reemplaza estos dos valores con los que te da SonarQube Cloud
sonar.projectKey=TU_ORG_TU-REPO
sonar.organization=TU_ORG

sonar.projectName=SQL Injection Lab
sonar.sources=.
sonar.exclusions=.venv/**,**/__pycache__/**,public/**

# Critico: sin esto el analisis asume Python 2+3 y silencia reglas
sonar.python.version=3.11

sonar.sourceEncoding=UTF-8
